In [15]:
# Tempturature Analysis
import numpy as np

# Define the current temp_celsius in the last 7 day 
temp_celsius = np.array([30.5, 32.0, 33.8, 31.1, 29.4, 28.9, 30.0])

# Find the average, maximun and minimun of the tempurature
temp_celsius_avr = np.mean(temp_celsius)
temp_celsius_max = np.max(temp_celsius)
temp_celsius_min = np.min(temp_celsius)

# Convert all the temp_celsius to Fahrenheit
temp_fahrenheit_avr = (temp_celsius_avr * 9/5) + 32
temp_fahrenheit_max = (temp_celsius_max * 9/5) + 32
temp_fahrenheit_min = (temp_celsius_min * 9/5) + 32

# Find the days (1 to 7) that had tempurature above 31.0 degree celsius
temp_celsius = np.sum(temp_celsius > 31.0)

# Display the results
print(f"The average tempurature in celsius is: {temp_celsius_avr} °C")
print(f"The maximum tempurature in celsius is: {temp_celsius_max} °C")
print(f"The minimum tempurature in celsius is: {temp_celsius_min} °C")
print(f"The average tempurature in Fahrenheit is: {temp_fahrenheit_avr} °F")
print(f"The maximum tempurature in Fahrenheit is: {temp_fahrenheit_max} °F")
print(f"The minimum tempurature in Fahrenheit is: {temp_fahrenheit_min} °F")
print(f"The number of days with tempurature above 31.0 °C is: {temp_celsius}")

The average tempurature in celsius is: 30.814285714285717 °C
The maximum tempurature in celsius is: 33.8 °C
The minimum tempurature in celsius is: 28.9 °C
The average tempurature in Fahrenheit is: 87.46571428571428 °F
The maximum tempurature in Fahrenheit is: 92.84 °F
The minimum tempurature in Fahrenheit is: 84.02 °F
The number of days with tempurature above 31.0 °C is: 3


In [16]:
# Student Score Analysis
import numpy as np 

# Define the student score for the exam
scores = np.array([65, 70, 85, 90, 55, 60, 75, 80])

# Find numbers of students whose passed (60 and above)
passed_stu = np.sum(scores >= 60)

# Find classes average score
avr_scores = np.mean(scores)

# Find the different between the highest score and the lowest score
score_diff = np.max(scores) - np.min(scores)

# Display results
print(f"Number of student that has passed the exam: {passed_stu}")
print(f"The average score of the class is: {avr_scores}")
print(f"The score difference between the highest score and the lowest score is: {score_diff}")

Number of student that has passed the exam: 7
The average score of the class is: 72.5
The score difference between the highest score and the lowest score is: 35


In [17]:
# Electricity Usage Analysis
import numpy as np

# Define the current week's usage
electricity_usage = np.array([30, 28, 35, 33, 32, 31, 29])

# Calculate next week's usage (applying a 5% increase)
# Multiplying by 1.05 increases each value by 5%
next_week_usage = electricity_usage * 1.05

# Find the average daily usage for next week
average_next_week = np.mean(next_week_usage)

# Find the total usage expected for next week
total_next_week = np.sum(next_week_usage)

# Display results
print(f"Average daily usage for next week: {average_next_week:.2f} kWh")
print(f"Total expected usage for next week: {total_next_week:.2f} kWh")

Average daily usage for next week: 32.70 kWh
Total expected usage for next week: 228.90 kWh


In [18]:
# Student Score Analysis
import numpy as np

# Define thee marks of the student scores out of 100
marks = np.array([40, 85, 30, 90, 70, 88, 95, 25])

# Marks equal or above 50
Passed_marks = marks[marks >= 50]

#  Amount ofo student who got above 80
Good_marks =np.sum(marks > 80)

# Add 5 marks to all students ( Capped at 100)
marks_with_bonus = np.minimum(marks + 5, 100)

# Replace all fail marks ( <50 ) with 50
marks_with_bonus_fail = np.where(marks_with_bonus < 50, 50, marks_with_bonus)

# Display results
print(f"Only 50 or more marks: {Passed_marks}")
print(f"Number of students who got above 80: {Good_marks}")
print(f"Marks after adding bonus (capped at 100): {marks_with_bonus}")
print(f"Marks after replacing fail marks with 50: {marks_with_bonus_fail}")



Only 50 or more marks: [85 90 70 88 95]
Number of students who got above 80: 4
Marks after adding bonus (capped at 100): [ 45  90  35  95  75  93 100  30]
Marks after replacing fail marks with 50: [ 50  90  50  95  75  93 100  50]


In [19]:
# Image Brightening and Darkening Adjustment
import numpy as np

# Define a 3x3 image with pixel values ranging from 0 to 255
image = np.array([
    [100, 120, 130],
    [140, 150, 160],
    [170, 180, 190]
])

# Create a brightened version of the image by adding 20 to each pixel value
brightened = np.minimum(image + 20, 255)

# Create a darkened version of the image by multiplying each pixel value by 0.85
darkened   = (image * 0.85).astype(int)

# Display results
print(f"Brightened Image: {brightened}")
print(f"Darkened Image: {darkened}")

Brightened Image: [[120 140 150]
 [160 170 180]
 [190 200 210]]
Darkened Image: [[ 85 102 110]
 [119 127 136]
 [144 153 161]]


In [27]:
# Stock Price Analysis
import numpy as np

# Define the stock prices for 5 consecutive days
prices = np.array([150, 152, 149, 153, 155])

# Calculate the daily returns as percentage change from the previous day
daily_returns = (np.diff(prices) / prices[:-1]) * 100

# Find the day with the highest and lowest stock price (1 to 5)
highest_day   = np.argmax(prices) + 1
lowest_day    = np.argmin(prices) + 1

# Calculate the overall profit percentage from the first day to the last day
profit_pct    = (prices[-1] - prices[0]) / prices[0] * 100

# Display results
print("Daily returns (percentage change compared to the previous day):")
for change in daily_returns:
    print(f"{change:.2f}%")
print(f"Day with Highest Price: Day {highest_day}")
print(f"Day with Lowest Price: Day {lowest_day}")
print(f"Profit/Loss % (buy→sell): {profit_pct:.2f}%")

Daily returns (percentage change compared to the previous day):
1.33%
-1.97%
2.68%
1.31%
Day with Highest Price: Day 5
Day with Lowest Price: Day 3
Profit/Loss % (buy→sell): 3.33%


In [ ]:
# Loan Default Risk Analysis
import numpy as np

# Define customer data: [age, income, debt]
customers = np.array([
    [25, 40000,  5000],
    [40, 80000, 15000],
    [35, 50000, 12000],
    [50,100000, 20000],
    [29, 60000,  8000]
])

# Calculate the debt-to-income ratio for each customer
dti_ratio    = customers[:, 2] / customers[:, 1]

# Identify customers with a debt-to-income ratio above 0.2
high_risk    = np.where(dti_ratio > 0.2)[0]

# Display results
print(f"Debt-to-Income Ratios: {dti_ratio}")
print(f"Customers with DTI ratio above 0.2: {high_risk}")

Debt-to-Income Ratios: [0.125      0.1875     0.24       0.2        0.13333333]
Customers with DTI ratio above 0.2: [2]


In [30]:
# Weather Data Cleaning
import numpy as np

# Simulate hourly temperature data for a week (7 days x 24 hours = 168 data points)
np.random.seed(42)
temperatures = np.random.choice(
    np.append(np.random.uniform(20, 35, size=160), [-999]*8),
    size=168, replace=False
)

# Replace -999 with the average of valid temperatures
valid_mean = np.mean(temperatures[temperatures != -999])
temperatures[temperatures == -999] = valid_mean

# Calculate the daily average temperature for each of the 7 days
daily_avg = temperatures.reshape(7, 24).mean(axis=1)

# Display results
print(f"Average of the non-missing temperatures: {valid_mean:.2f} °C")
print(f"Daily Average Temperatures: {daily_avg}")
print(f"Overall weekly average: {daily_avg.mean():.2f}°C")

Average of the non-missing temperatures: 27.16 °C
Daily Average Temperatures: [27.48526301 27.10643452 27.70055076 26.70471298 26.23339428 27.37643767
 27.49301204]
Overall weekly average: 27.16°C


In [36]:
# Flight Delay Analysis
import numpy as np

# Simulate flight delay data in minutes for 200 flights (positive for delays, negative for early arrivals)
np.random.seed(0)
delays = np.random.randint(-30, 180, size=200)

# Calculate the number of flights that were delayed (delays > 0) and the number of flights that arrived early (delays < 0)
n_delayed = np.sum(delays > 0)
n_early   = np.sum(delays < 0)

# Calculate the average delay time for delayed flights (delays > 0)
avg_delay = np.mean(delays[delays > 0])

# Identify the top 5% of delays (the worst delays)
top5_threshold = np.percentile(delays, 95)
worst_5pct     = delays[delays >= top5_threshold]

# Display results
print(f"Number of flights that were delayed (posive delays): {n_delayed}")
print(f"Number of flights that were delayed early (negative delays): {n_early}")
print(f"Average delay time for delayed flights: {avg_delay:.2f} minutes")
print(f"Top 5% of delays (worst delays): {worst_5pct}")

Number of flights that were delayed (posive delays): 172
Number of flights that were delayed early (negative delays): 27
Average delay time for delayed flights: 88.58 minutes
Top 5% of delays (worst delays): [178 167 172 173 173 174 177 167 175 171 179]


In [40]:
# Sales Data Analysis
import numpy as np

# Sales Data Analysis
week1 = np.array([200, 220, 250, 230, 240, 210, 260])
week2 = np.array([270, 280, 300, 310, 305, 295, 290])

# Calculate the overall average sales for the two weeks combined
all_sales   = np.concatenate([week1, week2])
overall_avg = np.mean(all_sales)

# Find the day with the highest increase in sales from week 1 to week 2 (1 to 7)
combined    = np.concatenate([week1, week2])
daily_diff  = np.diff(combined)
max_inc_day = np.argmax(daily_diff) + 2

# Display results
print(f"Overall average sales for the two weeks: {overall_avg:.2f}")
print(f"The Day With The Maximum increase compared to previous day: Day {max_inc_day}")

Overall average sales for the two weeks: 261.43
The Day With The Maximum increase compared to previous day: Day 7
