# Assignment 02

In [1]:
import numpy as np

In [2]:
# 1. Create array 1 to 10
a1 = np.arange(1, 11)
print(a1)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
# 2. Create array of zeros (10)
a2 = np.zeros(10)
print(a2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
# 3. Create array of ones (10)
a3 = np.ones(10)
print(a3)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [5]:
# 4. Create array of even numbers 2–20
a4 = np.arange(2, 21, 2)
print(a4) 

[ 2  4  6  8 10 12 14 16 18 20]


In [6]:
# 5. Create array of 10 random numbers (0–1)
a5 = np.random.rand(10)
print(a5)

[0.76084354 0.17653543 0.99284911 0.26120496 0.25864609 0.55612694
 0.39002332 0.58800474 0.85039787 0.64498943]


In [28]:
# 6. First 5 elements
a6 = a1[:5]
print(a6)

[1 2 3 4 5]


In [29]:
# 7. Last 5 elements
a7 = a1[-5:]
print(a7)

[ 6  7  8  9 10]


In [30]:
# 8. Reverse array
a8 = a1[::-1]
print(a8)

[10  9  8  7  6  5  4  3  2  1]


In [31]:
# 9. Elements from index 2 to 7
a9 = a1[2:8]
print(a9)

[3 4 5 6 7 8]


In [32]:
# 10. Even numbers from 1–50
a10 = np.arange(1, 51)
even = a10[a10 % 2 == 0]
print(a10)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


In [36]:
# 11. 4x5 random (0–10), filter rows
a11 = np.round(np.random.uniform(0, 10, (4, 5)), 1)
filtered = a11[(a11[:,1] > 2.0) & (a11[:,2] < 5.0)]
print(a11)
print(filtered)

[[0.5 9.2 2.6 5.1 6.4]
 [5.2 2.1 7.1 7.5 2.1]
 [6.9 3.4 8.1 9.1 0.5]
 [0.2 3.3 7.4 5.2 0.4]]
[[0.5 9.2 2.6 5.1 6.4]]


In [38]:
# 12. Replace numbers divisible by 2 or 3 but not both → -1
a12 = np.arange(1, 21)
cond = ((a12 % 2 == 0) ^ (a12 % 3 == 0))
a12[cond] = -1
print(a12)
print(cond)
print(a12[cond])

[ 1 -1 -1 -1  5  6  7 -1 -1 -1 11 12 13 -1 -1 -1 17 18 19 -1]
[False  True  True  True False False False  True  True  True False False
 False  True  True  True False False False  True]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]


In [39]:
# 13. 1D → 2D (5 rows)
a13 = np.arange(20).reshape(5, 4)
print(a13)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [40]:
# 14. 2D → 1D
a14 = a13.flatten()
print(a14)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [41]:
# 15. sum & mean
a15 = np.arange(1, 11)
sum_val = np.sum(a15)
mean_val = np.mean(a15)
print(a15)
print(sum_val)
print(mean_val)

[ 1  2  3  4  5  6  7  8  9 10]
55
5.5


In [42]:
# 16. sum of second column
a16 = np.random.randint(1, 10, (4, 5))
col_sum = np.sum(a16[:,1])
print(a16)
print(col_sum)

[[9 3 7 4 6]
 [9 6 4 9 1]
 [1 7 8 3 7]
 [9 1 2 8 7]]
17


In [43]:
# 17. mean of first 3 rows
mean_rows = np.mean(a16[:3])
print(mean_rows)

5.6


In [45]:
# 18. min per row & column
min_row = np.min(a16, axis=1)
min_col = np.min(a16, axis=0)
print(min_row)
print(min_col)

[3 1 1 1]
[1 1 2 3 1]


In [46]:
# 19. Remove duplicates
a19 = np.array([1,2,2,3,4,4,5])
unique = np.unique(a19)
print(a19)
print(unique)

[1 2 2 3 4 4 5]
[1 2 3 4 5]


In [47]:
# 20. Sort ascending & descending
a20 = np.random.randint(10, 21, 10)
asc = np.sort(a20)
desc = asc[::-1]
print(a20)
print(asc)
print(desc)

[13 12 12 13 11 16 12 18 20 10]
[10 11 12 12 12 13 13 16 18 20]
[20 18 16 13 13 12 12 12 11 10]


In [48]:
# 21. Merge arrays
a21_1 = np.array([1,2,3])
a21_2 = np.array([4,5,6])
merged = np.concatenate((a21_1, a21_2))
print(merged)

[1 2 3 4 5 6]


In [50]:
# 22. Common elements
a22_1 = np.random.randint(10, 21, 10)
a22_2 = np.random.randint(10, 21, 10)
common = np.intersect1d(a22_1, a22_2)
print(a22_1)
print(a22_2)
print(common)

[20 13 11 15 19 20 13 18 19 15]
[19 10 12 10 11 20 13 12 15 10]
[11 13 15 19 20]


In [51]:
# 23. Remove 1,2,3,4
a23 = np.random.randint(1, 11, 10)
filtered = a23[~np.isin(a23, [1,2,3,4])]
print(a23)
print(filtered)

[ 9  5 10  2  9  2  9  2  4  5]
[ 9  5 10  9  9  5]


In [52]:
# 24. Index of max value
a24 = np.arange(0.0, 5.1, 0.5)
max_index = np.argmax(a24)
print(a24)
print(max_index)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]
10


In [53]:
# 25. First even > 5
a25 = np.array([1,3,7,8,4,10])
idx = np.where((a25 % 2 == 0) & (a25 > 5))[0][0]
print(a25)
print(idx)

[ 1  3  7  8  4 10]
3


In [54]:
# 26. Add new column = col2 * col3
a26 = np.random.randint(1, 10, (4,5))
new_col = (a26[:,1] * a26[:,2]).reshape(-1,1)
result = np.hstack((a26, new_col))
print(a26)
print(new_col)
print(result)

[[5 6 2 1 7]
 [2 9 3 6 4]
 [9 7 3 3 8]
 [7 9 8 4 6]]
[[12]
 [27]
 [21]
 [72]]
[[ 5  6  2  1  7 12]
 [ 2  9  3  6  4 27]
 [ 9  7  3  3  8 21]
 [ 7  9  8  4  6 72]]
